// frontend/src/FolderOverlay.vue
<script setup>
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { LoaderCircle, Star, X } from 'lucide-vue-next'
import { listBooks, saveRating } from './api'
import { formatPercent } from './reader'

const props = defineProps({
  tag: String,
  search: {
    type: String,
    default: '',
  },
  status: {
    type: String,
    default: 'all',
  },
  minRating: {
    type: [String, Number],
    default: '',
  },
  sort: {
    type: String,
    default: 'title',
  },
})

const emit = defineEmits(['close', 'open'])

const books = ref([])
const loading = ref(false)
const error = ref('')
const currentPage = ref(0)
const ratingBookId = ref(null)
const ITEMS_PER_PAGE = 9

const totalPages = computed(() => Math.max(1, Math.ceil(books.value.length / ITEMS_PER_PAGE)))

const pageBooks = computed(() => {
  const start = currentPage.value * ITEMS_PER_PAGE
  return books.value.slice(start, start + ITEMS_PER_PAGE)
})

const effectiveSearch = computed(() => {
  const query = String(props.search || '').trim().toLowerCase()
  if (!query) return ''
  return String(props.tag || '').toLowerCase().includes(query) ? '' : props.search
})

function goPage(page) {
  currentPage.value = page
}

async function load() {
  if (!props.tag) return
  loading.value = true
  error.value = ''
  try {
    books.value = await listBooks({
      folderTag: props.tag,
      search: effectiveSearch.value,
      status: props.status,
      minRating: props.minRating,
      sort: props.sort || 'title',
    })
    currentPage.value = 0
  } catch (e) {
    error.value = e.message
  } finally {
    loading.value = false
  }
}

async function updateRating(book, rating) {
  const nextRating = book.rating === rating ? null : rating
  ratingBookId.value = book.id
  try {
    const updated = await saveRating(book.id, nextRating)
    const index = books.value.findIndex((item) => item.id === book.id)
    if (index !== -1) {
      books.value[index] = updated
    }
  } catch (e) {
    error.value = e.message
  } finally {
    ratingBookId.value = null
  }
}

watch(
  () => [props.tag, props.search, props.status, props.minRating, props.sort],
  () => { if (props.tag) load() },
  { immediate: true },
)

function handleKeydown(e) {
  if (e.key === 'Escape') {
    emit('close')
  } else if (e.key === 'ArrowLeft' && currentPage.value > 0) {
    currentPage.value--
  } else if (e.key === 'ArrowRight' && currentPage.value < totalPages.value - 1) {
    currentPage.value++
  }
}

onMounted(() => window.addEventListener('keydown', handleKeydown))
onBeforeUnmount(() => window.removeEventListener('keydown', handleKeydown))
</script>

<template>
  <Transition name="folder-overlay">
    <div v-if="tag" class="folder-overlay" @click.self="emit('close')">
      <div class="folder-panel">
        <header class="folder-panel-header">
          <strong>{{ tag }}</strong>
          <button class="icon-button" type="button" @click="emit('close')" title="关闭文件夹">
            <X :size="18" />
          </button>
        </header>

        <div v-if="loading" class="empty-state folder-loading">
          <LoaderCircle class="spin" :size="26" />
        </div>

        <p v-else-if="error" class="error">{{ error }}</p>

        <div v-else-if="books.length === 0" class="empty-state folder-empty">
          <p>此文件夹没有小说</p>
        </div>

        <template v-else>
          <div class="folder-grid">
            <article
              v-for="book in pageBooks"
              :key="book.id"
              class="folder-book"
              role="button"
              tabindex="0"
              @click="emit('open', book.id)"
              @keydown="(e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); emit('open', book.id) } }"
            >
              <strong class="folder-book-title">{{ book.title }}</strong>
              <span class="folder-book-progress">{{ formatPercent(book.progress) }}</span>
              <span class="folder-book-rating" @click.stop @keydown.stop>
                <button
                  v-for="r in 5"
                  :key="r"
                  class="folder-star-button"
                  :class="{ active: (book.rating || 0) >= r }"
                  type="button"
                  :disabled="ratingBookId === book.id"
                  :title="book.rating === r ? '清除评分' : `${r} 星`"
                  @click="updateRating(book, r)"
                >
                  <Star :size="12" />
                </button>
              </span>
            </article>
          </div>

          <div v-if="totalPages > 1" class="folder-dots">
            <button
              v-for="page in totalPages"
              :key="page"
              class="folder-dot"
              :class="{ active: currentPage === page - 1 }"
              :aria-label="`第 ${page} 页`"
              type="button"
              @click.stop="goPage(page - 1)"
            />
          </div>
        </template>
      </div>
    </div>
  </Transition>
</template>

// frontend/src/FolderOverlay.tsx
import { useEffect, useMemo, useState } from "react";
import { LoaderCircle, Star, X } from "lucide-react";
import { listBooks, saveRating } from "./api";
import { formatPercent } from "./reader";

const ITEMS_PER_PAGE = 9;

type FolderOverlayProps = {
  tag: string | null;
  search: string;
  status: string;
  minRating: string | number;
  sort: string;
  onClose: () => void;
  onOpen: (bookId: number) => void;
};

export default function FolderOverlay({
  tag,
  search,
  status,
  minRating,
  sort,
  onClose,
  onOpen,
}: FolderOverlayProps) {
  const [books, setBooks] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [currentPage, setCurrentPage] = useState(0);
  const [ratingBookId, setRatingBookId] = useState<number | null>(null);

  const effectiveSearch = useMemo(() => {
    const query = String(search || "").trim().toLowerCase();
    if (!query) return "";
    return String(tag || "").toLowerCase().includes(query) ? "" : search;
  }, [search, tag]);

  const totalPages = Math.max(1, Math.ceil(books.length / ITEMS_PER_PAGE));
  const pageBooks = books.slice(currentPage * ITEMS_PER_PAGE, currentPage * ITEMS_PER_PAGE + ITEMS_PER_PAGE);

  useEffect(() => {
    if (!tag) return;
    let cancelled = false;
    setLoading(true);
    setError("");
    (listBooks as any)({
      folderTag: tag,
      search: effectiveSearch,
      status,
      minRating,
      sort: sort || "title",
    })
      .then((nextBooks: any[]) => {
        if (!cancelled) {
          setBooks(nextBooks);
          setCurrentPage(0);
        }
      })
      .catch((err: Error) => {
        if (!cancelled) setError(err.message);
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [effectiveSearch, minRating, sort, status, tag]);

  useEffect(() => {
    function handleKeydown(event: KeyboardEvent) {
      if (!tag) return;
      if (event.key === "Escape") {
        onClose();
      } else if (event.key === "ArrowLeft" && currentPage > 0) {
        setCurrentPage((page) => page - 1);
      } else if (event.key === "ArrowRight" && currentPage < totalPages - 1) {
        setCurrentPage((page) => page + 1);
      }
    }

    window.addEventListener("keydown", handleKeydown);
    return () => window.removeEventListener("keydown", handleKeydown);
  }, [currentPage, onClose, tag, totalPages]);

  async function updateRating(book: any, rating: number) {
    const nextRating = book.rating === rating ? null : rating;
    setRatingBookId(book.id);
    setError("");
    try {
      const updated = await saveRating(book.id, nextRating);
      setBooks((items) => items.map((item) => (item.id === book.id ? updated : item)));
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setRatingBookId(null);
    }
  }

  if (!tag) return null;

  return (
    <div className="folder-overlay" onClick={(event) => {
      if (event.target === event.currentTarget) onClose();
    }}>
      <div className="folder-panel">
        <header className="folder-panel-header">
          <strong>{tag}</strong>
          <button className="icon-button" type="button" onClick={onClose} title="关闭文件夹">
            <X size={18} />
          </button>
        </header>

        {loading ? (
          <div className="empty-state folder-loading">
            <LoaderCircle className="spin" size={26} />
          </div>
        ) : error ? (
          <p className="error">{error}</p>
        ) : books.length === 0 ? (
          <div className="empty-state folder-empty">
            <p>此文件夹没有小说</p>
          </div>
        ) : (
          <>
            <div className="folder-grid">
              {pageBooks.map((book) => (
                <article
                  key={book.id}
                  className="folder-book"
                  role="button"
                  tabIndex={0}
                  onClick={() => onOpen(book.id)}
                  onKeyDown={(event) => {
                    if (event.key === "Enter" || event.key === " ") {
                      event.preventDefault();
                      onOpen(book.id);
                    }
                  }}
                >
                  <strong className="folder-book-title">{book.title}</strong>
                  <span className="folder-book-progress">{formatPercent(book.progress)}</span>
                  <span
                    className="folder-book-rating"
                    onClick={(event) => event.stopPropagation()}
                    onKeyDown={(event) => event.stopPropagation()}
                  >
                    {Array.from({ length: 5 }, (_, index) => {
                      const rating = index + 1;
                      return (
                        <button
                          key={rating}
                          className={`folder-star-button ${(book.rating || 0) >= rating ? "active" : ""}`}
                          type="button"
                          disabled={ratingBookId === book.id}
                          title={book.rating === rating ? "清除评分" : `${rating} 星`}
                          onClick={() => updateRating(book, rating)}
                        >
                          <Star size={12} />
                        </button>
                      );
                    })}
                  </span>
                </article>
              ))}
            </div>

            {totalPages > 1 && (
              <div className="folder-dots">
                {Array.from({ length: totalPages }, (_, index) => (
                  <button
                    key={index}
                    className={`folder-dot ${currentPage === index ? "active" : ""}`}
                    aria-label={`第 ${index + 1} 页`}
                    type="button"
                    onClick={(event) => {
                      event.stopPropagation();
                      setCurrentPage(index);
                    }}
                  />
                ))}
              </div>
            )}
          </>
        )}
      </div>
    </div>
  );
}
